# Load Data

In [1]:
import pandas as pd

df = pd.read_csv('data_for_ml.csv')
df.head()

,Hours_Studied,Sleep_Hours,Internet_Usage,Gender,Study_Method,Attendance,Final_Score
0,2.0,6.0,3.0,Male,Self Study,75.0,55.0
1,3.0,7.0,2.0,Female,Coaching,80.0,60.0
2,4.0,6.0,4.0,male,Self study,78.0,62.0
3,5.0,8.0,3.0,Femle,Group Study,85.0,70.0
4,6.0,7.0,5.0,Male,Self Study,88.0,72.0

# Check Missing Values

In [2]:
df.isnull().sum()

Hours_Studied     1
Sleep_Hours       1
Internet_Usage    1
Gender            1
Study_Method      1
Attendance        1
Final_Score       1
dtype: int64

# Handle Missing Values

In [3]:
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].mean())

# Remove Duplicates

In [4]:
df = df.drop_duplicates()

# Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

# Scaling

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Model Training

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

target = df.columns[-1]
results = []

for feature in df.columns[:-1][:5]:

    X = df[[feature]]
    y = df[target]

    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, random_state=42
    )

    model = LinearRegression()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    results.append({
        "Feature": feature,
        "MAE": mean_absolute_error(y_test, y_pred),
        "MSE": mean_squared_error(y_test, y_pred),
        "R2 Score": r2_score(y_test, y_pred)
    })

# Results

In [8]:
import pandas as pd

results_df = pd.DataFrame(results)
results_df

          Feature        MAE         MSE  R2 Score
0   Hours_Studied   3.316649   15.170253  0.935362
1     Sleep_Hours   5.449618   42.664800  0.818211
2  Internet_Usage   7.720368   71.814680  0.694007
3          Gender  13.697210  298.617698 -0.272371
4    Study_Method  13.601990  275.328817 -0.173140

# Best Model

In [9]:
results_df.sort_values(by='R2 Score', ascending=False)

          Feature        MAE         MSE  R2 Score
0   Hours_Studied   3.316649   15.170253  0.935362
1     Sleep_Hours   5.449618   42.664800  0.818211
2  Internet_Usage   7.720368   71.814680  0.694007
4    Study_Method  13.601990  275.328817 -0.173140
3          Gender  13.697210  298.617698 -0.272371